robot_cameras:
  floor_robot_camera: 
    active: false
    type: rgb
  
  ceiling_robot_camera: 
    active: false
    type: rgbd

static_sensors:
  conveyor_breakbeam:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.36, 3.5, 0.88]
      rpy: [0, 0, pi]
      
  right_bins_RGB_camera:
    type: rgb_camera
    pose:
      xyz: [-2.275, 3, 1.8]
      rpy: [pi, pi/2, 0]

  left_bins_RGB_camera:
    type: rgb_camera
    pose:
      xyz: [-2.275, -3, 1.8]
      rpy: [pi, pi/2, 0]
      
  right_bins_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-2.286, 2.96, 1.8]
      rpy: [pi, pi/2, 0]

  left_bins_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-2.286, -2.96, 1.8]
      rpy: [pi, pi/2, 0]

  kts1_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-1.3, -5.8, 1.8]
      rpy: [pi, pi/2, pi/2]
  
  kts2_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-1.3, 5.8, 1.8]
      rpy: [pi, pi/2, -pi/2]